import pandas as pd
import os
import seaborn as sns
import matplotlib.pyplot as plt
import sys
from statistics import geometric_mean

# Takes a csv file generated by the tiled spmv implementation and creates lots
# of plots.

if len(sys.argv) != 3:
    print("Usage: python3 ./plot/py parsed_datafile.csv plotdir")
    sys.exit(1)

datafile = sys.argv[1]
plotdir = sys.argv[2]

# Create plotdir if it doesn't already exist
if not os.path.exists(plotdir):
    os.mkdir(plotdir)

data = pd.read_csv(datafile)

xvals = ['rows', 'cols', 'nnz', 'pin']

sns.set_theme()

# Get columns 0, 4, 5, and 6 of the "data" DataFrame as a new dataframe
new_df = data[['nnz', 'pin', 'cusparse']]

# Get rows where pin is 1
df_pin = new_df[new_df['pin'] == 1]
df_no_pin = new_df[new_df['pin'] == 0]


data_pin = df_pin[['cusparse']].to_numpy()
data_no_pin = df_no_pin[['cusparse']].to_numpy()

speedup = data_no_pin / data_pin

print(speedup)

# Compute the geomean speedup
geomean = geometric_mean(speedup)

print("Geomean: {}".format(geomean))


dfm = new_df.melt('nnz', var_name='method', value_name='time')

plot = sns.scatterplot(data=dfm, x='nnz', y='time', hue='method')

# Set the x and y axis as log scale
plot.set(xscale="log", yscale="log")

# Set the y axis to use decimal notation
plot.get_yaxis().set_major_formatter(plt.FormatStrFormatter('%.2f'))

# Set the x and y axis labels
plot.set(xlabel='nnz', ylabel='time (s)')

# Set the title
plot.set_title('SpMV Benchmark')

# Save the plot as a file
plot.get_figure().savefig(os.path.join(plotdir, 'nnz_time.png'))
